### ISSUE TITLE
Bug in Intension to extension conversion

### ISSUE THREAD

**Issue by scand1sk** [xcsp3team/XCSP3-Java-Tools#11]
The instance `RoomMate/RoomMate-int-s1/RoomMate-sr0006-int.xml.lzma` that was used to test solvers before the XCSP 2017 Competition is reported to be satisfiable and have two solutions.

However, when the "convert intension to extension" option is activated (with an arity limit of 2), I get an exception `java.lang.RuntimeException: Constraint with only conflicts`.

I also have the same exception on the instance `RoomMate/RoomMate-int-s1/RoomMate-magic-10-50-int.xml.lzma` but as this one is unsatisfiable, it might be legit.

I updated to the latest commit (36f79e9) and still have the error.

**Comment by xcsp3team** [comment]
It was a bug at Lines 254 and 256 of CtrLoaderInteger.
Bug fixed.

**Comment by scand1sk** [comment]
Looks OK but a nasty println is left on Line 249 :)

**Comment by xcsp3team** [comment]
should be good now

**Comment by scand1sk** [comment]
Thank you :)
