### ISSUE TITLE
Intension to extension conversion of unary constraints may generate negative tables

### ISSUE THREAD

**Issue by scand1sk** [xcsp3team/XCSP3-Java-Tools#13]
On the instance `CryptoPuzzle-send-more-money` from the test library, there is a group of unary constraints built from the following snippet:
```xml
    <group>
      <intension> ne(%0,%1) </intension>
      <args> l[18] 0 </args>
      <args> l[12] 0 </args>
      <args> l[12] 0 </args>
    </group>
```

I spot two issues, one minor and one major with these constraints when the conversion from intension to extension is enabled:
1. callbacks for both intension and extension constraints are activated
2. the callback for unary constraints in extension is called. The tuples are a list of conflicts ({0}) but the `positive` flag is incorrectly set to `true`.

Thus, contradicting constraints are built and the problem is incorrectly reported to be unsatisfiable.

**Comment by xcsp3team** [comment]
Bug fixed.
It was occurring when RECOGNIZING_BEFORE_CONVERTING is set to Boolean.FALSE.

However, I was unable to reproduce the fact that both intension and extension constraints are posted. Can you check?

**Comment by scand1sk** [comment]
I pulled your bugfix, and issue 2. is indeed corrected. However, I can confirm that both intension and extension constraints are posted. I will try to investigate. 
The only parameter I gave to the callbacks (`implem` attribute) was to set `XCallbacksParameters.CONVERT_INTENSION_TO_EXTENSION_ARITY_LIMIT` to 2.

**Comment by scand1sk** [comment]
Apparently, for the constraint e.g. ne(l[18], 0), the method `recognizer.specificIntensionCases` calls the callback `buildCtrPrimitive(String, XVarInteger, TypeConditionOperatorRel, Int)` but returns `false`, which allows the extension callback to be called as well.
In the call stack, the `false` is caused by the check on Line 213 of `ConstraintRecognizer`.

Oh, I see. I overrided "implem" as a method, so that a new Implem is created every time a call to implem() is done, which causes some data to be lost. I have not checked whether this behavior is documented.

**Comment by xcsp3team** [comment]
When I execute with XCallbacksParameters.CONVERT_INTENSION_TO_EXTENSION_ARITY_LIMIT to 2.only,
I have the primitive intensional constraints posted, but not the extensional one.
Don't you call repost somewhere?

**Comment by scand1sk** [comment]
I have found the error and described the problem in my previous post: I overrided "implem" as a method, which instantiated a new Implem object every time it was called. This caused the check on Line 213 of `ConstraintRecognizer` to return `false`.
Is the fact that "implem" should always return the same instance documented?

**Comment by xcsp3team** [comment]
I will indeed add a remark in the next version of the parser documentation.
