### ISSUE TITLE
New release before the competition ?

### ISSUE THREAD

**Issue by cprudhom** [xcsp3team/XCSP3-Java-Tools#16]
Hi all,

Some bugs were fixed recently, is there a chance that a new release will be done before the competition starts or should we have to work with the master branch ?

Best

**Comment by xcsp3team** [comment]
Please, tell me what is your deadline for importing a new version (I could understand that you wanted to submit very soon), and I will tell you if it is compatible with my current activities.

**Comment by cprudhom** [comment]
I plan to do it tomorrow, but I can manage the submission with the master branch, no worries.
It is just that I was expecting a kind of official version.

**Comment by cprudhom** [comment]
When I run : `mvn package` I got 6 jars:
- xcsp3-competScope-1.0.1-SNAPSHOT.jar
- xcsp3-compiler-1.0.1-SNAPSHOT.jar
- xcsp3-solchecker-1.0.1-SNAPSHOT.jar
- xcsp3-tools-1.0.1-SNAPSHOT-javadoc.jar
- xcsp3-tools-1.0.1-SNAPSHOT-sources.jar
- xcsp3-tools-1.0.1-SNAPSHOT.jar

I selected the last one, is that correct ?

**Comment by xcsp3team** [comment]
Yes.
