### ISSUE TITLE
ASCII errors using gradle

### ISSUE THREAD

**Issue by toulbar2** [xcsp3team/XCSP3-Java-Tools#18]
Hi,
I had to modify two files to remove non-ascii characters in order to compile with gradle on my Linux ubuntu 16.04 LTS.
src/main/java/org/xcsp/modeler/api/ProblemAPI.java  (remove " symbols)

src/main/java/org/xcsp/modeler/definitions/ICtr.java
PATH line 47 had a weird accent Ä

**Comment by xcsp3team** [comment]
I have fixed the second problem.

For the first one, what do you mean?
All " symbols?

**Comment by toulbar2** [comment]
For the first file, the character around the operator name is non-ascii  (e.g. line 5368 numerical condition. When the operator "le")

**Comment by xcsp3team** [comment]
ok. I have changed these characters. Hoping that none remains.
