### ISSUE TITLE
BinPacking not recognized?

### ISSUE THREAD

**Issue by toulbar2** [xcsp3team/XCSP3-Java-Tools#19]
Checking the solution for checkingInstancesXCSP23/2023/BinPacking2.xml and BinPacking4.xml generates an error:

Exception in thread "main" org.xcsp.parser.WrongTypeException: Wrong parameter type in constraint:
binPacking()
	list() : [x[0], x[1], x[2], x[3], x[4], x[5], x[6], x[7], x[8], x[9]]
	sizes() : 10, 2, 6, 11, 21, 4, 8, 3, 8, 10
	limits() : 24, 18, 22, 21

**Comment by thibaultfalque** [comment]
I have the same problem :slightly_frowning_face:

**Comment by xcsp3team** [comment]
This is fixed.

**Comment by xcsp3team** [comment]
I will make a new release very soon
