### ISSUE TITLE
Wrong unsatisfied constraint is reported by SolutionChecker

### ISSUE THREAD

**Issue by scand1sk** [xcsp3team/XCSP3-Java-Tools#2]
Given instance `Crossword-lex-vg-5-5` and the following instantiation:

`<instantiation>
      <list>
        x[0][0] x[0][1] x[0][2] x[0][3] x[0][4] x[1][0] x[1][1] x[1][2] x[1][3] x[1][4] x[2][0] x[2][1] x[2][2] x[2][3] x[2][4] x[3][0] x[3][1] x[3][2] x[3][3] x[3][4] x[4][0] x[4][1] x[4][2] x[4][3] x[4][4]
      </list>
      <values>
        2 7 8 13 0 17 4 13 0 11 4 17 0 3 4 18 14 13 8 2 18 13 4 0 10
      </values>
    </instantiation>`

The instantiation does not satisfy the third constraint (scope x[2][]) but the satisfied tenth constraint (scope x[][4]) is reported as invalid.

From what I understand, it seems that `SolutionChecker` adds `currCtr` to a list of invalid constraints (line 211 of commit 8d626cd), but `currCtr` is actually a mutable template which is modified afterwards. As a quick hack, one could save the invalid constraint's String representation to avoid mutability.

**Comment by xcsp3team** [comment]
Yes, you are right.
I am going to fix the problem.

**Comment by xcsp3team** [comment]
New version committed.
Is that ok for you ?

**Comment by scand1sk** [comment]
Mmh, just storing the constraint's id may be unsufficient for debugging usage, as the id is generated by the checker and it's hard to find out which actual constraint in the model is affected.

**Comment by xcsp3team** [comment]
I have modified the output.

**Comment by scand1sk** [comment]
OK it should be fine now, thank you
