### ISSUE TITLE
SolutionChecker does not detect bad AlldifferentMatrix solutions

### ISSUE THREAD

**Issue by scand1sk** [xcsp3team/XCSP3-Java-Tools#3]
Given this Latin Square model (based on Latin Square instances found in the XCSP3 series database):
```
<instance format="XCSP3" type="CSP">
  <variables>
    <array id="x" size="[3][3]"> 0..2 </array>
  </variables>
  <constraints>
    <allDifferent>
      <matrix> x[][] </matrix>
    </allDifferent>
  </constraints>
</instance>
```

and the instantiation:
```
<instantiation>
      <list>
        x[0][0] x[0][1] x[0][2] x[1][0] x[1][1] x[1][2] x[2][0] x[2][1] x[2][2]
      </list>
      <values>
        1 0 0 0 1 0 2 0 0
      </values>
    </instantiation>
```

The solution is incorrect but SolutionChecker does not detect it. It seems that it is based on a wrong interpretation of the AllDifferentMatrix constraint. All values from any given row/column must be all different. It seems that SolutionChecker is based on "all rows/columns are different".

**Comment by xcsp3team** [comment]
You are right.
I have pushed a corrected version.
Is that ok for you ?

**Comment by scand1sk** [comment]
Yes it should be OK now.
