### ISSUE TITLE
Parser: eq(a, eq(b, c)) should not be optimized to eq(a, b, c)

### ISSUE THREAD

**Issue by scand1sk** [xcsp3team/XCSP3-Java-Tools#4]
It seems that the parser "optimizes" intensions of the form `eq(a, eq(b, c))` to `eq(a, b, c)`.

The optimization is incorrect. In the former formula, `eq(b, c)` returns a boolean value specifying whether b is equal to c (ie, reified equality). The semantics is different. 

Admitedly, according to the XCSP3 specification, the formula should be written `iff(a, eq(b, c))`, but `iff` and `eq` have similar semantics on booleans.

**Comment by xcsp3team** [comment]
Allright.
Bug fixed.
I'll commit in a moment. Please, check.
