### ISSUE TITLE
ifThen constraints are not properly parsed

### ISSUE THREAD

**Issue by scand1sk** [xcsp3team/XCSP3-Java-Tools#7]
I want to parse a problem that features ifThen constraints of the form:

`<ifThen>
<intension>eq(vars[0][0],13)</intension>
<intension>eq(vars[0][1],14)</intension>
</ifThen>`

It seems that this constraint is not parsed correctly. The `XParser.parseCEntry` method does not contain any branch that matches ifThen constraint (or IfThenElse if I am correct), so the "child" array is not filled correctly. This leads to an ArrayIndexOutOfBoundsException in XParser.parseCEntryOuter.

**Comment by xcsp3team** [comment]
New methods have been inserted.
Whenever a logic-based meta-constraint <and>, <or> <not>, <ifThen> or <ifThenElse> is parsed, the method  loadLogic of XCallBacks is called. On your side, you have to override the methods beginLogic and endLogic. 

Is that ok for you?

**Comment by scand1sk** [comment]
Sorry, but beginLogic and endLogic are not called. I get an ArrayIndexOutOfBoundsException on line 

https://github.com/xcsp3team/XCSP3-Java-Tools/blob/41387a959c8572b8c096a135b1d10223721d7ae0/src/main/java/org/xcsp/parser/XParser.java#L1133

because `entry.childs` is empty although `lastSon == 1`. Note that it seems that the `sons` array is correctly filled with the two intensional subconstraints.

Here is the full file I want to parse, maybe it can help you spotting my issue.

[ModelFile.xml.gz](https://github.com/xcsp3team/XCSP3-Java-Tools/files/1608174/ModelFile.xml.gz)

**Comment by xcsp3team** [comment]
Bug should be Fixed now.
I succeeded in parsing your file until one badly formed  intensional expression was found.
Indeed, you have  expressions of the form : ne(vars[][0],14).
This is not valid. What do you mean?
Every variable at column 0 must be not equal to 14?

**Comment by xcsp3team** [comment]
Is that good for you, Julien ?

**Comment by scand1sk** [comment]
Yes I forgot to close the issue. Thank you. Another one incoming.
