### ISSUE TITLE
Provide maven dependency

### ISSUE THREAD

**Issue by rtaupe** [xcsp3team/XCSP3-Java-Tools#8]
Hi,

it would be great if it was possible to add xcsp3 as a dependency to maven projects. For example, [choco-parsers](https://github.com/chocoteam/choco-parsers) is provided on maven but [cannot be included as a dependency because it depends on xcsp3](https://github.com/chocoteam/choco-parsers) in turn.

Thank you for your consideration!

**Comment by xcsp3team** [comment]
Hi,
 We have added a pom.xml in the repository.
We have opened an issue on Maven central.
We will let you informed.

**Comment by xcsp3team** [comment]
This is now added to maven Central.

**Comment by rtaupe** [comment]
Great, thanks!
